name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        mvn -B package -DskipTests --file raf3k/pom.xml

    - name: Run Maven tests
      run: |
        mvn test --file raf3k/pom.xml
